[project]
name = "pyail"
version = "0.0.13"
description = "Python API for AIL"
authors = [
    {name="Aurelien Thirion (terrtia)", email="<aurelien.thirion@circl.lu>"}
]
license = "BSD-2-Clause"

readme = "README.md"

[project.urls]
repository = "https://github.com/ail-project/PyAIL"
issues = "https://github.com/ail-project/PyAIL/issues"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.23.0"

[poetry.group.dev.dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=2.0"]
build-backend = "poetry.masonry.api"
